env:
  global:
    - secure:  "CgEp7fvcC6HxUT4ziTBx9vcWmlqUnlfBXUknPXLJHC31bpJvH+N7St8DJDw+LL0bfjE8keZJJQnX+k1PzSBTfUhMIh5JeOpLwyQlhONToTT8SXsM9J8Rw0yzMH6YRSW8ExlyQ867sS/sOpV/jKMb+nL1AyBMSwUIxt2ZHtapMhdbUQGV/EGt6BXuwVfQGvWrlnktOsaZlAB20hPe6/bpnltYKXvNWBSNjwej3rBuxJqgQZDXmYickADvVkJQRg7digM0AjyJGfvjgE+WTfcohDTFWW/La65a6viL40xBOHQj8VhL58/KpvKU12Or9q+FfhUih9Ecov988gNTcl40kuayRrYySpXut86PMA5dQ2aQzr9MgetSFKJqiJTRB1iWFI0jsLKZXLLIZ2a2y+GxxhdKTrrhpWP28jaByb7crnT7TeXDmtHS0nxWcgFEMTDU4ZpTkgYLkksL4/X38OQgIgY57MxEhIoCC3CQefq21A9ISqHRzGt5nuCcyUYnVCgPdjESae9aAxGOpMrT4hYInP8qI5zPsZX2Gyb7oznbL0USVqRvbF4rRDKheILR7KVE18lzUzekmFjxSUIrCNOiUbeaw0D2detPhZag0oQl8WUNVN8AKOKZye18Dfu77t3LIdN4rK80xBt0JvEU5wWsGwsc0voGP6n9pWwl5QLh2ag="
sudo: false
language: node_js
node_js: stable
after_success:
  - |
        $(npm bin)/set-up-ssh --key "$encrypted_102af6f1c923_key" \
                              --iv "$encrypted_102af6f1c923_iv" \
                              --path-encrypted-key ".travis/github_deploy_key.enc"

        $(npm bin)/update-branch --commit-message "Update website [skip ci]" \
                                 --directory "./example" \
                                 --distribution-branch "gh-pages" \
                                 --source-branch "master"
